#!/usr/bin/python3
'''Module for parameterized testing of utils.access_nested_map'''
from parameterized import parameterized
import unittest
from utils import access_nested_map

class TestAccessNestedMap(unittest.TestCase):
    def test_access_nested_map(self):
        @parameterized.expand([
            ({"a": 1}, ("a",), 1),
            ({"a": {"b": 2}}, ("a",), {"b": 2}),
            ({"a": {"b": 2}}, ("a", "b"), 2)
        ])
if __name__ == '__main__':
    TestAccessNestedMap.run()
